In [1]:
#here all the procedure is same as that of previous
#here logistic regression(with test_size=0.15) is used and 
#k=10 is taken in feature selection method (i.e select kbest)
#accuracy is 79.47%

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data=pd.read_csv('telco.csv')
data.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ...  DeviceProtection  \
0  No phone service             DSL             No  ...                No   
1                No             DSL            Yes  ...               Yes   
2                No             DSL            Yes  ...                No   
3  No phone service             DSL            Yes  ...               Yes   
4                No     Fiber optic             No  ...                No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
customerID          7043 non-null object
gender              7043 non-null object
SeniorCitizen       7043 non-null int64
Partner             7043 non-null object
Dependents          7043 non-null object
tenure              7043 non-null int64
PhoneService        7043 non-null object
MultipleLines       7043 non-null object
InternetService     7043 non-null object
OnlineSecurity      7043 non-null object
OnlineBackup        7043 non-null object
DeviceProtection    7043 non-null object
TechSupport         7043 non-null object
StreamingTV         7043 non-null object
StreamingMovies     7043 non-null object
Contract            7043 non-null object
PaperlessBilling    7043 non-null object
PaymentMethod       7043 non-null object
MonthlyCharges      7043 non-null float64
TotalCharges        7043 non-null object
Churn               7043 non-null object
dtypes: float64(1), int64(2), obj

In [5]:
data1=data[['tenure','MonthlyCharges']]

In [6]:
data=data.drop(['customerID','TotalCharges'],axis=1)

In [7]:
from sklearn.preprocessing import LabelEncoder
data=data.apply(LabelEncoder().fit_transform)

In [8]:
data.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0   
1       1              0        0           0      34             1   
2       1              0        0           0       2             1   
3       1              0        0           0      45             0   
4       0              0        0           0       2             1   

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0              1                0               0             2   
1              0                0               2             0   
2              0                0               2             2   
3              1                0               2             0   
4              0                1               0             0   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 0            0            0                0         0   
1                 2            0            0                0         1   
2                 0            0            0                0         0   
3                 2            2            0                0         1   
4                 0            0            0                0         0   

   PaperlessBilling  PaymentMethod  MonthlyCharges  Churn  
0                 1              2             142      0  
1                 0              3             498      0  
2                 1              3             436      1  
3                 0              0             266      0  
4                 1              2             729      1

In [9]:
data['Churn'].value_counts()# it is not imbalance

0    5174
1    1869
Name: Churn, dtype: int64

In [10]:
x=data.iloc[:,:-1] # x is with categorical data
y=data.iloc[:,-1:]

In [11]:
x.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0   
1       1              0        0           0      34             1   
2       1              0        0           0       2             1   
3       1              0        0           0      45             0   
4       0              0        0           0       2             1   

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0              1                0               0             2   
1              0                0               2             0   
2              0                0               2             2   
3              1                0               2             0   
4              0                1               0             0   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 0            0            0                0         0   
1                 2            0            0                0         1   
2                 0            0            0                0         0   
3                 2            2            0                0         1   
4                 0            0            0                0         0   

   PaperlessBilling  PaymentMethod  MonthlyCharges  
0                 1              2             142  
1                 0              3             498  
2                 1              3             436  
3                 0              0             266  
4                 1              2             729

In [12]:
x1=x.drop(['tenure','MonthlyCharges'],axis=1) #x1 is having only categorical data
x1.head()

gender  SeniorCitizen  Partner  Dependents  PhoneService  MultipleLines  \
0       0              0        1           0             0              1   
1       1              0        0           0             1              0   
2       1              0        0           0             1              0   
3       1              0        0           0             0              1   
4       0              0        0           0             1              0   

   InternetService  OnlineSecurity  OnlineBackup  DeviceProtection  \
0                0               0             2                 0   
1                0               2             0                 2   
2                0               2             2                 0   
3                0               2             0                 2   
4                1               0             0                 0   

   TechSupport  StreamingTV  StreamingMovies  Contract  PaperlessBilling  \
0            0            0                0         0                 1   
1            0            0                0         1                 0   
2            0            0                0         0                 1   
3            2            0                0         1                 0   
4            0            0                0         0                 1   

   PaymentMethod  
0              2  
1              3  
2              3  
3              0  
4              2

In [13]:
x1['PaymentMethod'].unique()

array([2, 3, 0, 1], dtype=int64)

In [14]:
x1['PaymentMethod'].value_counts()

2    2365
3    1612
0    1544
1    1522
Name: PaymentMethod, dtype: int64

In [15]:
x1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 16 columns):
gender              7043 non-null int32
SeniorCitizen       7043 non-null int64
Partner             7043 non-null int32
Dependents          7043 non-null int32
PhoneService        7043 non-null int32
MultipleLines       7043 non-null int32
InternetService     7043 non-null int32
OnlineSecurity      7043 non-null int32
OnlineBackup        7043 non-null int32
DeviceProtection    7043 non-null int32
TechSupport         7043 non-null int32
StreamingTV         7043 non-null int32
StreamingMovies     7043 non-null int32
Contract            7043 non-null int32
PaperlessBilling    7043 non-null int32
PaymentMethod       7043 non-null int32
dtypes: int32(15), int64(1)
memory usage: 467.8 KB


In [16]:
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest

In [17]:
pre_model=SelectKBest(chi2,k=10)
x_kbest=pre_model.fit_transform(x1,y)

In [18]:
pre_model.get_support()# to know the which best features are selected by kbest method

array([False,  True,  True,  True, False, False, False,  True,  True,
        True,  True, False, False,  True,  True,  True])

In [19]:
x_kbest=pd.DataFrame(x_kbest)
x_kbest.head()

0  1  2  3  4  5  6  7  8  9
0  0  1  0  0  2  0  0  0  1  2
1  0  0  0  2  0  2  0  1  0  3
2  0  0  0  2  2  0  0  0  1  3
3  0  0  0  2  0  2  2  1  0  0
4  0  0  0  0  0  0  0  0  1  2

In [20]:
x_kbest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 10 columns):
0    7043 non-null int64
1    7043 non-null int64
2    7043 non-null int64
3    7043 non-null int64
4    7043 non-null int64
5    7043 non-null int64
6    7043 non-null int64
7    7043 non-null int64
8    7043 non-null int64
9    7043 non-null int64
dtypes: int64(10)
memory usage: 550.3 KB


In [21]:
x_kbest.shape

(7043, 10)

In [22]:
data1.head()

tenure  MonthlyCharges
0       1           29.85
1      34           56.95
2       2           53.85
3      45           42.30
4       2           70.70

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [24]:
data1=sc.fit_transform(data1)

C:\Users\shree\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\shree\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [25]:
type(data1)

numpy.ndarray

In [26]:
data1=pd.DataFrame(data1)
data1=data1.rename(columns={0:'tenure',1:'MonthlyCharges'})

In [27]:
data1.head()

tenure  MonthlyCharges
0 -1.277445       -1.160323
1  0.066327       -0.259629
2 -1.236724       -0.362660
3  0.514251       -0.746535
4 -1.236724        0.197365

In [28]:
df=pd.concat([data1,x_kbest],axis=1) # merge two dataframes
df.head()

tenure  MonthlyCharges  0  1  2  3  4  5  6  7  8  9
0 -1.277445       -1.160323  0  1  0  0  2  0  0  0  1  2
1  0.066327       -0.259629  0  0  0  2  0  2  0  1  0  3
2 -1.236724       -0.362660  0  0  0  2  2  0  0  0  1  3
3  0.514251       -0.746535  0  0  0  2  0  2  2  1  0  0
4 -1.236724        0.197365  0  0  0  0  0  0  0  0  1  2

In [29]:
from sklearn.model_selection import train_test_split as tts
xtrain,xtest,ytrain,ytest=tts(df,y,test_size=0.15,random_state=0)

In [30]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(xtrain,ytrain)

C:\Users\shree\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\shree\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [31]:
ypred=lr.predict(xtest)

In [32]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score
accuracy_score(ytest,ypred)

0.7947019867549668

In [33]:
confusion_matrix(ytest,ypred)

array([[710,  81],
       [136, 130]], dtype=int64)

In [34]:
precision_score(ytest,ypred)

0.6161137440758294

In [35]:
recall_score(ytest,ypred)

0.48872180451127817